name: Deploy Tumya

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test TCP Connection
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          nc -vz ${{ secrets.HOST }} 22

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            echo "Connected successfully"